name: RBP Demo
run-name: ${{github.actor}} is testing
on: [push]
jobs:
  testing:
    runs-on: self-hosted
    steps:
      - run: echo "Hello world"
      - run: |
          echo "Test files" >> example.txt
          echo "pwd"
          uname -a
